armor_tracker_node:
  ros__parameters:
    # 步长
    dt: 0.1

    # 初始状态的速度 
    u_vel: 10.0
    v_vel: 0.2
    u_a: 2.0
    v_a: 0.0

    # 测量噪声 Q （6*6）
    Q: [1.0,  0.0,  0.05,  0.0,  0.005,  0.0,
        0.0,  0.05,  0.0,  0.05,  0.0,  0.005,
        0.05,  0.0,  1.0,  0.0,  0.05,  0.0,
        0.0,  0.05,  0.0,  0.05,  0.0,  0.05,
        0.005,  0.0,  0.05,  0.0,  1.0,  0.0,
        0.0,  0.005,  0.0,  0.05,  0.0,  0.05]

    # 观测噪声 R (2*2)
    R: [0.05, 0.0,
        0.0, 0.05]