armor_tracker_node:
  ros__parameters:
    # 初始状态的速度 
    u_vel: 1.0
    v_vel: 0.2
    u_a: 1.0
    v_a: 0.0

    Q: [0.1,  0.0,  0.01,  0.0,  0.001,  0.0,
        0.0,  0.1,  0.0,  0.01,  0.0,  0.001,
        0.01,  0.0,  0.1,  0.0,  0.01,  0.0,
        0.0,  0.01,  0.0,  0.1,  0.0,  0.01,
        0.001,  0.0,  0.01,  0.0,  0.1,  0.0,
        0.0,  0.001,  0.0,  0.01,  0.0,  0.1]

    # 观测噪声 R (2x2)
    R: [0.05, 0.0,
        0.0, 0.05]